### ISSUE TITLE
This page doesn't explain how to pass username and password for postgress despite the fields existing

### ISSUE THREAD

**Issue by jhancock-taxa** [dotnet/docs-aspire#1009]
The fields are some sort of parameter which isn't documented how to specify a parameter with value and there doesn't seem to be any examples of this.

Further, because you can't set this, pgadmin has a magical password that it prompts for but you don't know what it is, so you're stuck with a useless pgadmin as currently documented.

---
[Associated WorkItem - 261092](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261092)

**Comment by IEvangelist** [comment]
Hi @JHTaxa - what page are you referring to here?

**Comment by JHTaxa** [comment]
https://learn.microsoft.com/en-us/dotnet/aspire/database/postgresql-component?tabs=dotnet-cli

(sorry thought it automatically did it when providing feedback from the page)

Basically if you use data persistence, then you must set username and password because the random password that is the default won't work.

There's @davidfowl notes on this in several other places.

His solution is to set it in app secrets, but I'd rather configure it directly and explicitly and even if this isn't possible, his comments should be transfered into direct instructions with notes about data persistence on this page.
