### ISSUE TITLE
dotnet publish p:PublishProfile=DefaultContainer errors out

### ISSUE THREAD

**Issue by alexhiggins732** [dotnet/docs-aspire#128]
### Type of issue

Code doesn't work

### Description

The dotnet publish command throws in the documentation throws an error after installing the start kit in Visual Studio.

```
A publish profile with the name 'DefaultContainer' was not found in the project

```

![image](https://github.com/dotnet/docs-aspire/assets/2246388/a095a746-8a99-46b5-9113-295bf034f488)

Not sure if the there is supposed to be a default publish profile in the template. After manually adding Docker publish profiles to the web and ApiService I was able to publish the containers.

This seems confusing. What is the point of the AppHost? Is that what is supposed to be published?

### Page URL

https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment?tabs=visual-studio%2Cinstall-az-windows%2Cpowershell&pivots=azure-cli

### Content source URL

https://github.com/dotnet/docs-aspire/blob/main/docs/deployment/azure/aca-deployment.md

### Document Version Independent Id

1362fc62-686d-2b3f-c139-7725fc8dca5f

### Article author

@IEvangelist

**Comment by IEvangelist** [comment]
Let's ask @baronfel - perhaps he is familiar with this error?

**Comment by baronfel** [comment]
The AppHost doesn't import the Publish SDK, which is what provides that default profile. The AppHost itself doesn't provide and publishable content, so we may want to look into suppressing that warning for AppHost projects, but do to MSBuild semantics you can't pass a property via the command line to just a few projects, so this is the world we're stuck in.

One thing we could do (and IMO should do starting in 8.0.200) is move towards using the PublishContainer MSBuild target in docs instead of the PublishProfile method. The Target is more broadly available than the PublishProfile is, and can be specified at the command line in 8.0.2xx without causing warnings.

**Comment by IEvangelist** [comment]
> The AppHost doesn't import the Publish SDK, which is what provides that default profile. The AppHost itself doesn't provide and publishable content, so we may want to look into suppressing that warning for AppHost projects, but do to MSBuild semantics you can't pass a property via the command line to just a few projects, so this is the world we're stuck in.
> 
> One thing we could do (and IMO should do starting in 8.0.200) is move towards using the PublishContainer MSBuild target in docs instead of the PublishProfile method. The Target is more broadly available than the PublishProfile is, and can be specified at the command line in 8.0.2xx without causing warnings.

But couldn't you check if the project has the `IsAspireHost` bit set, and then do conditional warnings? Like when that it `true` don't have warnings?

As for `PublishContainer` vs `PublishProfile`, yeah, happy to help make that happen - but need to know a bit more about what that looks like.

**Comment by baronfel** [comment]
We can't do those conditional checks you mention because the thing firing the warnings isn't in the Aspire components, rather it's in a completely unrelated set of props/targets. You wouldn't add an Aspire-specific condition there because it mixes concerns. 

As for what the Target version of publishing looks like, take a look over at https://github.com/richlander/container-workshop - Rich and I have been working on a workshop/patterns that show off the capabilities of .NET Containers on a hands-on way there!

**Comment by IEvangelist** [comment]
Closing as I cannot re-produce and this is an old issue.
