### ISSUE TITLE
[CSS]: Articles should have an appropriate reading time

### ISSUE THREAD

**Issue by HugoDurana** [dotnet/docs-aspire#2100]
### Article title

All articles

### Article URL

All articles

### Description

Please review articles for how long should one take to read them, as several other pieces of documentation across the Microsoft set already have this and helps with planning for training activities.

**Comment by IEvangelist** [comment]
This is a platform feature that existed for a long time but has since been removed as we had lots of customers disagreeing with the calculated read times. If this is something that you feel strongly about, you could try reaching out to @meganbradley as she at the very least would know the proper channel for such a request.
