### ISSUE TITLE
Module 9: Deploy a .NET Aspire App to Azure

### ISSUE THREAD

**Issue by bradygaster** [dotnet/docs-aspire#449]
---
[Associated WorkItem - 239426](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239426)

**Comment by alistairmatthews** [comment]
Module is ready for review. 
[PR](https://github.com/MicrosoftDocs/learn-pr/pull/45202)
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/deploy-dotnet-aspire-app-azure/?branch=pr-en-us-45202)

**Comment by bradygaster** [comment]
@alistairmatthews i tried to do this today and it looks like the staging link is inaccurate; could you update it?

**Comment by alistairmatthews** [comment]
It's already been merged to the NEW-deploy-aspire-azure branch. I don't think there's a staging location now. I guess you have to do a PR to main so that it generates one? Content is here now: https://github.com/MicrosoftDocs/learn-pr/tree/NEW-deploy-aspire-azure/learn-pr/aspnetcore/deploy-dotnet-aspire-app-azure

**Comment by alistairmatthews** [comment]
[New PR for Brady's review](https://github.com/MicrosoftDocs/learn-pr/pull/45353)
[Staging link](https://review.learn.microsoft.com/en-us/training/modules/deploy-dotnet-aspire-app-azure/?branch=pr-en-us-45353)
