### ISSUE TITLE
Rework Deployment Section

### ISSUE THREAD

**Issue by bradygaster** [dotnet/docs-aspire#548]
### Describe the issue or suggestion

During triage we discussed making some changes to the deployment section. @alexwolfmsft might have additions - feel free to make comments and we'll re-work. 

- [ ] Rework the ACA article to provide options for deploying via command line with AZD and via Visual Studio
- [ ] Make sure the 2 CI/CD articles are up-to-date (GitHub Actions and AzDO Pipelines)
- [ ] Add an article on customizing one's deployment that goes into using `azd infra synth` for IAC generation and customization
- [ ] Add a new "production considerations" article that walks through a few of the suggested changes one would need to make post-`azd infra synth` to production-ready their apps. One thing we'd want to call out here is how to add a managed identity and role assignments **per container app** rather than using 1 single managed identity for the whole app
- [ ] Cover the upcoming changes in the App Host-located provisioning code - those specific to the `Construct` approaches that are beginning to percolate throughout preview 5 - and explain how developers can use the `RunAs` and/or `PublishAs` methods to customize the deployment scenarios

---
[Associated WorkItem - 238741](https://dev.azure.com/msft-skilling/Content/_workitems/edit/238741)

**Comment by bradygaster** [comment]
cc @mitchdenny and @glennc to see if you had any addendums to the production section above or any additional concerns you think we'd need to mitigate. We're marking this with `preview-5` but I feel confident we'll extend this as the updates come in for the provisioning changes.

**Comment by timheuer** [comment]
Maybe another TODO is how to address in docs any commentary on k8s (and AKS) deployment at this time.

**Comment by alexwolfmsft** [comment]
A couple thoughts here @bradygaster 

Right now we have AZD, Bicep and CLI steps for ACA deployment. I agree we should prioritize AZD and Visual Studio (which we currently don't have) - but I'm assuming we also still want Azure CLI and Bicep. These approaches are much more manual, so my recommendation would be to keep them but reduce the size of those flows by extracting the CLI commands and Bicep code into completed scripts in the aspire-samples repo and provide an overview of them rather than keeping the tedious copy/paste approach of those currently. That way the simpler approaches are front and center and the other approaches are there if people want them.

I also think we should have some sort of (short) AZD + Aspire overview doc that is non specific to any one scenario that explains concepts such as:
- Which Azure services are supported for auto provisioning/deployment
- The relationship between AZD and .NET Aspire - basically extracting most of the content out of the existing "in-depth" tutorial into it's own section about how AZD consumes the resource info to "auto provision" via in-memory. I think the in-depth tutorial should go away personally, since that content would be handled by this new doc plus the improved standard aca deployment tutorial
- Basics of infra synth
- Basics of CI/CD option through AZD

The goal would be for these topics to provide context for the other docs that use AZD for specific scenarios since these are shared concepts.

**Comment by mitchdenny** [comment]
Your summary looks good Brady. I think calling out the managed identity thing is good. It really depends on your architecture to determine whether that is something you would be concerned about. For example, if you are just using a single compute resource and a bunch of Azure resources then a single managed identity is probably fine. Beyond that it just comes down to your preference around blast radius.

**Comment by glennc** [comment]
I am late to noticing this but seems good to me.

**Comment by bradygaster** [comment]
@alexwolfmsft did we lose the "production considerations" item? I didn't see that in the doc to which you linked and this is coming back up as a big deal for 9.0 we'd like to have implemented.
